"""
Django settings for renew_website project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

import environ
import os
import warnings

# Suppress "StreamingHttpResponse must consume synchronous iterators" warning 
# caused by WhiteNoise/FileResponse in ASGI mode.
warnings.filterwarnings("ignore", message="StreamingHttpResponse must consume synchronous iterators")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
PROJECT_DIR = os.path.join(BASE_DIR, "renew_website")

# Initialise environment variables
env = environ.Env(
    DEBUG=(bool, False)
)

# Reading .env file
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# In production, SECRET_KEY must be set in environment variables
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=True)

# Allowed hosts - in development allow all, in production configure via env
if DEBUG:
    ALLOWED_HOSTS = ['*']
else:
    ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['localhost', '127.0.0.1'])

# CSRF trusted origins for production
CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS', default=['http://localhost:8000'])

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Local apps
    'renew_website.apps.accounts',
    'renew_website.apps.admin',
    'renew_website.apps.charging_stations',
    'renew_website.apps.public',
    'renew_website.apps.api',
    'renew_website.apps.api.v1',
    'renew_website.apps.api.deye',
    'renew_website.apps.api.energy',
    'renew_website.apps.api.weather',
        # Third-party apps
    'channels',
    'rest_framework',
    'django_filters',
    'drf_spectacular',
    'corsheaders',
    # Celery
    'django_celery_beat',
    'django_celery_results',
]

# Channel Layers Configuration
# Use Redis in production, InMemory for development
REDIS_URL = env('REDIS_URL', default=None)

if REDIS_URL and not DEBUG:
    # Production: Use Redis channel layer (scalable, persistent)
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [REDIS_URL],
                "capacity": 1500,  # Maximum messages in channel
                "expiry": 60,  # Message expiry in seconds
            },
        },
    }
else:
    # Development: Use InMemory channel layer (single process only)
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer"
        }
    }

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS - must be before CommonMiddleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'renew_website.apps.accounts.middleware.SessionTrackingMiddleware',  # Custom session tracking
]

ROOT_URLCONF = 'renew_website.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(PROJECT_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

ASGI_APPLICATION = 'renew_website.asgi.application'
WSGI_APPLICATION = 'renew_website.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env('POSTGRES_DB', default='renew_db'),
        'USER': env('POSTGRES_USER', default='renew_user'),
        'PASSWORD': env('POSTGRES_PASSWORD', default='changeme'),
        'HOST': env('POSTGRES_HOST', default='db'),
        'PORT': env('POSTGRES_PORT', default='5432'),
    }
}

# DATABASE_ROUTERS = ['renew_website.routers.DatabaseRouter']


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Sofia'

USE_I18N = True

#USE_TZ = True
USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = 'public:index'
LOGOUT_REDIRECT_URL = 'public:index'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Add these settings at the end of the file
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# For Django 4.2+ add this setting
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# =============================================================================
# Security Settings
# =============================================================================

# Session security
SESSION_COOKIE_AGE = 86400  # 24 hours
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_COOKIE_HTTPONLY = True

# Production security settings (enabled when DEBUG=False)
if not DEBUG:
    # HTTPS settings
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    
    # Cookie security
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    
    # HSTS (HTTP Strict Transport Security)
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # Content security
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = 'DENY'

# =============================================================================
# Logging Configuration
# =============================================================================

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'django.log'),
            'maxBytes': 10485760,  # 10 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': env('DJANGO_LOG_LEVEL', default='INFO'),
            'propagate': False,
        },
        'charging_stations': {
            'handlers': ['console'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        'ocpp': {
            'handlers': ['console'],
            'level': 'WARNING',  # Reduce OCPP library logging (heartbeats, etc.)
            'propagate': False,
        },
    },
}

# Create logs directory if it doesn't exist
os.makedirs(os.path.join(BASE_DIR, 'logs'), exist_ok=True)

# ... (rest of the code remains the same)
# Django REST Framework Configuration
# =============================================================================

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# JWT Settings
from datetime import timedelta as jwt_timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': jwt_timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': jwt_timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
}

# API Documentation (drf-spectacular)
SPECTACULAR_SETTINGS = {
    'TITLE': 'EV Charging Platform API',
    'DESCRIPTION': 'REST API for managing EV charging stations, sessions, and users',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

# =============================================================================
# CORS Configuration
# =============================================================================

CORS_ALLOWED_ORIGINS = env.list('CORS_ALLOWED_ORIGINS', default=[
    'http://localhost:3000',
    'http://localhost:8000',
])
CORS_ALLOW_CREDENTIALS = True

# =============================================================================
# DeyeCloud API Configuration
# =============================================================================

DEYE_APP_ID = env('DEYE_APP_ID', default=None)
DEYE_APP_SECRET = env('DEYE_APP_SECRET', default=None)
DEYE_EMAIL = env('DEYE_EMAIL', default=None)
DEYE_PASSWORD = env('DEYE_PASSWORD', default=None)
DEYE_DATACENTER = env('DEYE_DATACENTER', default='eu')  # 'eu' or 'us'
DEYE_COMPANY_ID = env('DEYE_COMPANY_ID', default='0')   # '0' for personal accounts

# Hardware Identifiers (From .env)
DEYE_MASTER_SN = env('DEYE_MASTER_SN', default='2409109016')
DEYE_SLAVE_SN = env('DEYE_SLAVE_SN', default='2409109073')
DEYE_MASTER_LOGGER_SN = env('DEYE_MASTER_LOGGER_SN', default='3117882047')
DEYE_SLAVE_LOGGER_SN = env('DEYE_SLAVE_LOGGER_SN', default='3117079603')

# Local Connection Settings
# IP-то на Wi-Fi логъра на Master инвертора
DEYE_MASTER_LOCAL_IP = env('DEYE_MASTER_LOCAL_IP', default='192.168.88.253')
DEYE_SLAVE_LOCAL_IP = env('DEYE_SLAVE_LOCAL_IP', default='192.168.88.254') 

# Режим на свързване: 'cloud' (през интернет), 'local' (през мрежата) или 'auto'
DEYE_CONNECTION_MODE = env('DEYE_CONNECTION_MODE', default='cloud')
# =============================================================================
# Celery Configuration
# =============================================================================
CELERY_BROKER_URL = env('CELERY_BROKER_URL', default='redis://redis:6379/0')
CELERY_RESULT_BACKEND = env('CELERY_RESULT_BACKEND', default='redis://redis:6379/0')
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# Celery Beat Schedule
from celery.schedules import crontab
CELERY_BEAT_SCHEDULE = {
    'sample_task': {
        'task': 'renew_website.tasks.sample_task',
        'schedule': 30.0,
    },
    'sync-modbus-every-30-seconds': {
        'task': 'sync_all_stations_modbus',
        'schedule': 30.0,
    },
    'fetch-weather-every-15-minutes': {
        'task': 'renew_website.apps.api.weather.tasks.fetch_weather_task',
        'schedule': crontab(minute='*/15'),
    },
    'fetch-inverter-every-5-minutes': {
        'task': 'renew_website.apps.api.deye.tasks.fetch_inverter_telemetry',
        'schedule': crontab(minute='*/5'),
    },
    'store-inverter-readings-every-5-minutes': {
        'task': 'renew_website.apps.api.energy.tasks.store_inverter_readings_task',
        'schedule': crontab(minute='*/5'),
    }
}