# Generated by Django 5.2 on 2025-08-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('connector_type', models.CharField(max_length=50)),
                ('power_output', models.IntegerField()),
                ('access_type', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('members', 'Members Only')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Under Maintenance')], max_length=20)),
                ('rate', models.CharField(blank=True, max_length=50)),
                ('contact_email', models.EmailField(max_length=254)),
                ('network', models.CharField(max_length=100)),
            ],
        ),
    ]
