# Generated by Django 5.2 on 2025-08-20 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charging_stations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='station',
            old_name='contact_email',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='station',
            name='access_type',
        ),
        migrations.RemoveField(
            model_name='station',
            name='network',
        ),
        migrations.RemoveField(
            model_name='station',
            name='rate',
        ),
    ]
