# Generated by Django 5.2 on 2025-09-23 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging_stations', '0002_rename_contact_email_station_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connector_id', models.IntegerField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('faulted', 'Faulted')], default='available', max_length=20)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connectors', to='charging_stations.station')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.IntegerField()),
                ('id_tag', models.CharField(max_length=50)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('meter_start', models.IntegerField()),
                ('meter_stop', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('stopped', 'Stopped'), ('error', 'Error')], default='active', max_length=20)),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='charging_stations.connector')),
            ],
        ),
        migrations.CreateModel(
            name='MeterValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('value', models.IntegerField()),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meter_values', to='charging_stations.transaction')),
            ],
        ),
    ]
