# Generated by Django 5.2 on 2026-03-16 12:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charging_stations", "0002_alter_station_ocpp_identity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="connector",
            name="connector_number",
            field=models.IntegerField(
                default=1,
                help_text="Human-readable connector number (1-based: 1, 2, 3...)",
            ),
        ),
        migrations.AddField(
            model_name="connector",
            name="is_primary",
            field=models.BooleanField(
                default=False, help_text="This is the primary connector for the station"
            ),
        ),
        migrations.AddField(
            model_name="connector",
            name="phases",
            field=models.CharField(
                choices=[("1", "Single Phase"), ("3", "Three Phase")],
                default="1",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="connector",
            name="connector_type",
            field=models.CharField(
                choices=[
                    ("type2", "Type 2"),
                    ("ccs", "CCS"),
                    ("chademo", "CHAdeMO"),
                    ("type1", "Type 1"),
                    ("tesla", "Tesla"),
                    ("schuko", "Schuko"),
                ],
                default="type2",
                help_text="Physical connector type",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="connector",
            name="max_current_a",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("32.0"),
                help_text="Maximum current this connector can draw (A)",
                max_digits=6,
            ),
        ),
        migrations.AlterField(
            model_name="connector",
            name="max_power_kw",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("22.0"),
                help_text="Maximum power this connector can deliver (kW)",
                max_digits=6,
            ),
        ),
        migrations.AlterField(
            model_name="connector",
            name="supports_smart_charging",
            field=models.BooleanField(
                default=True,
                help_text="Connector supports smart charging/load balancing",
            ),
        ),
        migrations.AlterField(
            model_name="connector",
            name="voltage_v",
            field=models.IntegerField(
                default=230, help_text="Voltage this connector operates at (V)"
            ),
        ),
    ]
