# Generated by Django 5.2 on 2025-09-23 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging_stations', '0003_connector_transaction_metervalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='requested_power_kw',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
