# Generated by Django 5.2 on 2025-09-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging_stations', '0004_transaction_requested_power_kw'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRFID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tag', models.CharField(max_length=50, unique=True)),
                ('owner_name', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
