# Generated by Django 5.2 on 2025-09-23 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging_stations', '0005_userrfid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connector',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('preparing', 'Preparing'), ('charging', 'Charging'), ('suspendedEV', 'SuspendedEV'), ('suspendedEVSE', 'SuspendedEVSE'), ('finishing', 'Finishing'), ('reserved', 'Reserved'), ('faulted', 'Faulted'), ('offline', 'Offline')], default='available', max_length=20),
        ),
    ]
