# Generated by Django 5.2 on 2025-10-01 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charging_stations', '0006_alter_connector_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_id',
        ),
    ]
