# Generated by Django 5.2 on 2025-10-01 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charging_stations', '0007_remove_transaction_transaction_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrfid',
            old_name='id_tag',
            new_name='tag',
        ),
        migrations.RemoveField(
            model_name='connector',
            name='connector_id',
        ),
    ]
