# Generated by Django 5.2 on 2025-10-15 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging_stations', '0009_alter_station_latitude_alter_station_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='connector',
            name='connector_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
