# Generated by Django 5.2 on 2025-10-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging_stations', '0010_connector_connector_id_transaction_transaction_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connector',
            options={'ordering': ['station', 'connector_id']},
        ),
        migrations.AlterField(
            model_name='connector',
            name='connector_id',
            field=models.IntegerField(help_text='Physical connector number at this station (e.g., 1, 2, 3)'),
        ),
        migrations.AlterUniqueTogether(
            name='connector',
            unique_together={('station', 'connector_id')},
        ),
    ]
