# Generated by Django 5.2 on 2025-10-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging_stations', '0011_alter_connector_options_alter_connector_connector_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='station',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_id',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id_tag',
            field=models.CharField(help_text='RFID tag used for this transaction', max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='meter_start',
            field=models.IntegerField(default=0, help_text='Starting meter value in Wh'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='meter_stop',
            field=models.IntegerField(blank=True, help_text='Ending meter value in Wh', null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='requested_power_kw',
            field=models.IntegerField(blank=True, help_text='Requested charging power in kW', null=True),
        ),
    ]
