# Generated by Django 5.2 on 2025-10-15 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging_stations', '0012_alter_station_options_alter_transaction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connector',
            name='availability',
            field=models.CharField(choices=[('operative', 'Operative'), ('inoperative', 'Inoperative')], default='operative', max_length=20),
        ),
    ]
