# Generated by Django 5.2 on 2025-10-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging_stations', '0013_connector_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='metervalue',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
