# Generated by Django 5.2 on 2025-11-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging_stations', '0014_metervalue_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='connector',
            name='vendor_connector_id',
            field=models.CharField(blank=True, help_text="Vendor's alphanumeric identifier for this connector (if available)", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Under Maintenance')], default='inactive', max_length=20),
        ),
    ]
