# Generated by Django 5.2 on 2025-11-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging_stations', '0015_connector_vendor_connector_id_alter_station_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='connector',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, help_text="When this connector's status was last updated"),
        ),
        migrations.AddField(
            model_name='station',
            name='serial_number',
            field=models.CharField(blank=True, help_text="Vendor's serial number for this station (e.g., TACW2245324G0135)", max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='connector',
            name='vendor_connector_id',
            field=models.CharField(blank=True, help_text="Vendor's alphanumeric identifier for this connector. For single-connector stations, this often matches the station's serial number.", max_length=50, null=True),
        ),
    ]
