# Generated by Django 5.2 on 2025-11-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging_stations', '0016_connector_last_updated_station_serial_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='last_seen',
            field=models.DateTimeField(blank=True, help_text='When this station was last online', null=True),
        ),
        migrations.AlterField(
            model_name='connector',
            name='vendor_connector_id',
            field=models.CharField(blank=True, help_text="Vendor's alphanumeric identifier for this connector. For single-connector stations, this is typically the station's serial number from the WebSocket URL.", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='serial_number',
            field=models.CharField(blank=True, help_text="Vendor's serial number for this station", max_length=50, null=True, unique=True),
        ),
    ]
