# Generated by Django 5.2 on 2025-11-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging_stations', '0017_station_last_seen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='serial_number',
        ),
        migrations.AddField(
            model_name='station',
            name='model',
            field=models.CharField(blank=True, help_text='Model identifier for the charging station (e.g., TACW22-G0135)', max_length=50, null=True),
        ),
    ]
