# Generated by Django 5.2 on 2025-11-14 13:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging_stations', '0018_remove_station_serial_number_station_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userrfid',
            options={'ordering': ['owner_name', 'tag'], 'verbose_name': 'User RFID', 'verbose_name_plural': 'User RFIDs'},
        ),
        migrations.AddField(
            model_name='userrfid',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='When this RFID was registered'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userrfid',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this RFID is currently active'),
        ),
        migrations.AddField(
            model_name='userrfid',
            name='notes',
            field=models.TextField(blank=True, help_text='Any additional notes about this RFID'),
        ),
        migrations.AddField(
            model_name='userrfid',
            name='stations',
            field=models.ManyToManyField(blank=True, help_text='Stations this RFID can access', related_name='authorized_users', to='charging_stations.station'),
        ),
        migrations.AlterField(
            model_name='userrfid',
            name='owner_name',
            field=models.CharField(blank=True, help_text='Name of the RFID card owner', max_length=100),
        ),
        migrations.AlterField(
            model_name='userrfid',
            name='tag',
            field=models.CharField(help_text='The RFID tag number', max_length=50, unique=True),
        ),
    ]
