# Generated by Django 5.2 on 2025-11-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging_stations', '0019_alter_userrfid_options_userrfid_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrfid',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, help_text='When this record was last updated'),
        ),
    ]
