# Generated by Django 5.2 on 2026-01-05 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charging_stations", "0020_userrfid_last_updated"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PricingPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the pricing plan", max_length=100
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "price_per_kwh",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Price per kWh in local currency",
                        max_digits=6,
                    ),
                ),
                (
                    "connection_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="One-time fee for connecting (session start)",
                        max_digits=6,
                    ),
                ),
                (
                    "idle_fee_per_minute",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="Fee per minute after charging completes (to discourage overstaying)",
                        max_digits=6,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("EUR", "Euro"),
                            ("USD", "US Dollar"),
                            ("GBP", "British Pound"),
                            ("BGN", "Bulgarian Lev"),
                        ],
                        default="EUR",
                        max_length=3,
                    ),
                ),
                (
                    "peak_multiplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        help_text="Multiplier for peak hours (e.g., 1.5 = 50% more)",
                        max_digits=4,
                    ),
                ),
                (
                    "peak_hours_start",
                    models.TimeField(
                        blank=True, help_text="Start of peak hours", null=True
                    ),
                ),
                (
                    "peak_hours_end",
                    models.TimeField(
                        blank=True, help_text="End of peak hours", null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Pricing Plan",
                "verbose_name_plural": "Pricing Plans",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ChargingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "energy_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Cost for energy consumed",
                        max_digits=10,
                    ),
                ),
                (
                    "connection_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Connection/session start fee",
                        max_digits=10,
                    ),
                ),
                (
                    "idle_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Fee for idle time after charging",
                        max_digits=10,
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total cost for this session",
                        max_digits=10,
                    ),
                ),
                ("currency", models.CharField(default="EUR", max_length=3)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("payment_reference", models.CharField(blank=True, max_length=100)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "energy_kwh",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        help_text="Energy delivered in kWh",
                        max_digits=10,
                    ),
                ),
                ("duration_minutes", models.IntegerField(default=0)),
                ("idle_minutes", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing",
                        to="charging_stations.transaction",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="charging_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pricing_plan",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sessions",
                        to="charging_stations.pricingplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Charging Session",
                "verbose_name_plural": "Charging Sessions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("card", "Credit/Debit Card"),
                            ("wallet", "Digital Wallet"),
                            ("invoice", "Invoice"),
                        ],
                        default="card",
                        max_length=20,
                    ),
                ),
                ("card_last_four", models.CharField(blank=True, max_length=4)),
                ("card_brand", models.CharField(blank=True, max_length=20)),
                ("card_expiry_month", models.IntegerField(blank=True, null=True)),
                ("card_expiry_year", models.IntegerField(blank=True, null=True)),
                ("provider", models.CharField(default="stripe", max_length=50)),
                (
                    "provider_payment_method_id",
                    models.CharField(blank=True, max_length=100),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_methods",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Method",
                "verbose_name_plural": "Payment Methods",
                "ordering": ["-is_default", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_number", models.CharField(max_length=50, unique=True)),
                ("issue_date", models.DateField(auto_now_add=True)),
                ("due_date", models.DateField()),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "tax_rate",
                    models.DecimalField(decimal_places=2, default=20.0, max_digits=5),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("currency", models.CharField(default="EUR", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent"),
                            ("paid", "Paid"),
                            ("overdue", "Overdue"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sessions",
                    models.ManyToManyField(
                        related_name="invoices", to="charging_stations.chargingsession"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payment_method",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="charging_stations.paymentmethod",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice",
                "verbose_name_plural": "Invoices",
                "ordering": ["-issue_date"],
            },
        ),
        migrations.CreateModel(
            name="StationPricing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, help_text="Default pricing for this station"
                    ),
                ),
                ("valid_from", models.DateTimeField(blank=True, null=True)),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                (
                    "pricing_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="station_configs",
                        to="charging_stations.pricingplan",
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricing_configs",
                        to="charging_stations.station",
                    ),
                ),
            ],
            options={
                "verbose_name": "Station Pricing",
                "verbose_name_plural": "Station Pricing",
                "unique_together": {("station", "pricing_plan")},
            },
        ),
    ]
