# Generated by Django 5.2 on 2026-01-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "charging_stations",
            "0021_pricingplan_chargingsession_paymentmethod_invoice_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={"ordering": ["-started_at"]},
        ),
        migrations.AddField(
            model_name="transaction",
            name="cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total cost of charging session",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="pricing_plan",
            field=models.CharField(
                blank=True, help_text="Pricing plan used", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="transaction_id",
            field=models.CharField(
                blank=True,
                help_text="OCPP transaction UUID",
                max_length=36,
                null=True,
                unique=True,
            ),
        ),
    ]
