# Generated by Django 5.2 on 2026-01-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "charging_stations",
            "0022_alter_transaction_options_transaction_cost_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="connector",
            name="connector_type",
            field=models.CharField(
                choices=[
                    ("type2", "Type 2"),
                    ("ccs", "CCS"),
                    ("chademo", "CHAdeMO"),
                    ("type1", "Type 1"),
                    ("tesla", "Tesla"),
                ],
                default="type2",
                help_text="Physical connector type",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="connector",
            name="current_power_kw",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Current power being delivered (kW)",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="connector",
            name="energy_delivered_kwh",
            field=models.DecimalField(
                decimal_places=4,
                default=0.0,
                help_text="Total energy delivered through this connector (kWh)",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="connector",
            name="max_current_a",
            field=models.DecimalField(
                decimal_places=2,
                default=32.0,
                help_text="Maximum current this connector can draw (A)",
                max_digits=6,
            ),
        ),
        migrations.AddField(
            model_name="connector",
            name="max_power_kw",
            field=models.DecimalField(
                decimal_places=2,
                default=22.0,
                help_text="Maximum power this connector can deliver (kW)",
                max_digits=6,
            ),
        ),
        migrations.AddField(
            model_name="connector",
            name="supports_smart_charging",
            field=models.BooleanField(
                default=True,
                help_text="Whether this connector supports smart charging/power limiting",
            ),
        ),
        migrations.AddField(
            model_name="connector",
            name="voltage_v",
            field=models.IntegerField(default=230, help_text="Operating voltage (V)"),
        ),
    ]
