# Generated by Django 5.2 on 2026-03-16 18:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "charging_stations",
            "0024_connector_connector_number_connector_is_primary_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="connector",
            name="connector_id",
            field=models.IntegerField(
                help_text="Physical connector number at this station as defined by the charge point (OCPP connectorId)."
            ),
        ),
        migrations.AlterField(
            model_name="connector",
            name="current_power_kw",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AlterField(
            model_name="connector",
            name="energy_delivered_kwh",
            field=models.DecimalField(
                decimal_places=4, default=Decimal("0.0"), max_digits=10
            ),
        ),
    ]
