# Generated by Django 5.2 on 2026-03-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charging_stations", "0025_alter_connector_connector_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chargingsession",
            name="user",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="user",
        ),
        migrations.RemoveField(
            model_name="paymentmethod",
            name="user",
        ),
        migrations.AddField(
            model_name="chargingsession",
            name="user_id",
            field=models.IntegerField(
                blank=True, help_text="Reference to auth.User ID (SQLite)", null=True
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="user_id",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                help_text="Reference to auth.User ID (SQLite)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="user_id",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                help_text="Reference to auth.User ID (SQLite)",
                null=True,
            ),
        ),
    ]
