# Generated by Django 5.2 on 2026-03-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging_stations', '0026_remove_chargingsession_user_remove_invoice_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='ocpp_identity',
            field=models.CharField(blank=True, help_text='OCPP Identity (ChargeBox Identity)', max_length=255, null=True),
        ),
    ]
