# Generated by Django 5.2 on 2026-04-29 08:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charging_stations", "0027_station_ocpp_identity"),
    ]

    operations = [
        migrations.AddField(
            model_name="metervalue",
            name="energy_wh",
            field=models.IntegerField(
                blank=True, help_text="Total energy consumed (Wh)", null=True
            ),
        ),
        migrations.AddField(
            model_name="metervalue",
            name="power_w",
            field=models.IntegerField(
                blank=True, help_text="Current charging power (W)", null=True
            ),
        ),
        migrations.AddField(
            model_name="metervalue",
            name="soc_percentage",
            field=models.FloatField(
                blank=True, help_text="State of Charge (%)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="metervalue",
            name="timestamp",
            field=models.DateTimeField(
                default=django.utils.timezone.now, help_text="Момент на измерването"
            ),
        ),
        migrations.AlterField(
            model_name="metervalue",
            name="value",
            field=models.IntegerField(
                blank=True,
                help_text="Стойноста на брояча (ако не се ползва energy_wh)",
                null=True,
            ),
        ),
    ]
