# Generated by Django 5.2 on 2026-05-12 00:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charging_stations", "0028_metervalue_energy_wh_metervalue_power_w_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommandLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("command_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("command_type", models.CharField(max_length=64)),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("sent", "Sent"), ("failed", "Failed")],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("detail", models.TextField(blank=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "station",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.deletion.SET_NULL,
                        related_name="command_logs",
                        to="charging_stations.station",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="commandlog",
            index=models.Index(fields=["station", "status"], name="charging_st_station_2ad7aa_idx"),
        ),
        migrations.AddIndex(
            model_name="commandlog",
            index=models.Index(fields=["command_type", "created_at"], name="charging_st_command_b8d724_idx"),
        ),
        migrations.AddIndex(
            model_name="commandlog",
            index=models.Index(fields=["created_at"], name="charging_st_created_dc9c31_idx"),
        ),
    ]