# Generated by Django 5.2 on 2026-05-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging_stations', '0028_metervalue_energy_wh_metervalue_power_w_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='Local IP address for Modbus/API access', null=True),
        ),
    ]
