# Generated by Django 5.2 on 2026-05-12 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charging_stations", "0029_commandlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commandlog",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("sent", "Sent"),
                    ("acknowledged", "Acknowledged"),
                    ("rejected", "Rejected"),
                    ("timeout", "Timeout"),
                    ("failed", "Failed"),
                    ("failed_at_station", "Failed At Station"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]