# Generated by Django 5.2 on 2026-05-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charging_stations", "0029_station_ip_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="stop_reason",
            field=models.CharField(
                blank=True,
                help_text="Reason from OCPP StopTransaction.req",
                max_length=50,
                null=True,
            ),
        ),
    ]
