# Generated by Django 5.2 on 2026-05-14 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging_stations', '0033_station_runtime_environment'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='last_applied_ems_limit_kw',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Latest EMS-applied charging power ceiling for this session in kW.', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='requested_power_mode',
            field=models.CharField(choices=[('manual', 'Manual Limit'), ('auto', 'Auto / EV Negotiated'), ('station-default', 'Station Default')], default='station-default', help_text='How the requested charging power was selected for this session.', max_length=20),
        ),
    ]
