# Generated by Django 5.2 on 2026-05-14 17:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def seed_station_status_history(apps, schema_editor):
    Station = apps.get_model('charging_stations', 'Station')
    StationStatusHistory = apps.get_model('charging_stations', 'StationStatusHistory')

    rows = []
    for station in Station.objects.all().iterator():
        rows.append(
            StationStatusHistory(
                station_id=station.id,
                status=station.status,
                reason='migration-seed',
                observed_at=station.last_seen or django.utils.timezone.now(),
            )
        )

    if rows:
        StationStatusHistory.objects.bulk_create(rows)


class Migration(migrations.Migration):

    dependencies = [
        ('charging_stations', '0034_transaction_last_applied_ems_limit_kw_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Under Maintenance')], max_length=20)),
                ('reason', models.CharField(blank=True, default='', max_length=64)),
                ('observed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='charging_stations.station')),
            ],
            options={
                'ordering': ['-observed_at', '-id'],
                'indexes': [models.Index(fields=['station', 'observed_at'], name='charging_st_station_b641bb_idx'), models.Index(fields=['status', 'observed_at'], name='charging_st_status_bff2d2_idx')],
            },
        ),
        migrations.RunPython(seed_station_status_history, migrations.RunPython.noop),
    ]
