# Generated by Django 5.2.3 on 2025-08-05 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserPersona',
            new_name='UserPosition',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='persona',
            new_name='position',
        ),
    ]
