# Generated by Django 5.2 on 2026-01-09 14:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EVChargingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vehicle_id", models.CharField(max_length=100)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "target_soc",
                    models.IntegerField(help_text="Target battery percentage"),
                ),
                (
                    "current_soc",
                    models.IntegerField(help_text="Current battery percentage"),
                ),
                (
                    "max_power",
                    models.FloatField(help_text="Maximum charging power in watts"),
                ),
                (
                    "optimized_schedule",
                    models.JSONField(
                        default=dict, help_text="Algorithm's charging schedule"
                    ),
                ),
                (
                    "actual_energy_used",
                    models.FloatField(
                        help_text="Actual energy consumed in kWh", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="GridPricing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                (
                    "price_per_kwh",
                    models.FloatField(help_text="Price in local currency per kWh"),
                ),
                ("is_peak", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["start_time"],
            },
        ),
        migrations.CreateModel(
            name="Inverter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_sn", models.CharField(max_length=50, unique=True)),
                ("device_id", models.IntegerField()),
                ("device_type", models.CharField(max_length=50)),
                ("product_id", models.CharField(max_length=50)),
                ("station_id", models.IntegerField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="WeatherForecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                (
                    "cloud_cover",
                    models.FloatField(help_text="Cloud coverage percentage", null=True),
                ),
                (
                    "solar_irradiance",
                    models.FloatField(help_text="Solar irradiance in W/m²", null=True),
                ),
                (
                    "temperature",
                    models.FloatField(help_text="Temperature in Celsius", null=True),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="InverterReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "generation_power",
                    models.FloatField(
                        help_text="Current power generation in watts", null=True
                    ),
                ),
                (
                    "battery_soc",
                    models.FloatField(
                        help_text="Battery state of charge percentage", null=True
                    ),
                ),
                (
                    "grid_power",
                    models.FloatField(help_text="Grid power flow in watts", null=True),
                ),
                (
                    "station_data",
                    models.JSONField(
                        default=dict, help_text="Raw station data from API"
                    ),
                ),
                (
                    "connect_status",
                    models.IntegerField(
                        default=1, help_text="Device connection status"
                    ),
                ),
                (
                    "collection_time",
                    models.DateTimeField(
                        help_text="Last data collection time", null=True
                    ),
                ),
                (
                    "inverter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="readings",
                        to="energy.inverter",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["inverter", "timestamp"],
                        name="energy_inve_inverte_99ca72_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="energy_inve_timesta_06c210_idx"
                    ),
                ],
            },
        ),
    ]
