# Generated by Django 5.2 on 2026-01-14 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("energy", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EVChargingSession",
        ),
    ]
