# Generated by Django 5.2 on 2026-03-16 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0003_workmode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeatherForecast',
        ),
    ]
