# Generated by Django 5.2 on 2026-03-16 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("energy", "0004_delete_weatherforecast"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkMode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("selling_first", "Selling First"),
                            ("zero_export_load", "Zero Export to Load"),
                            ("zero_export_ct", "Zero Export to CT"),
                        ],
                        help_text="Current work mode",
                        max_length=20,
                    ),
                ),
                (
                    "control_mode",
                    models.CharField(
                        choices=[("automatic", "Automatic"), ("manual", "Manual")],
                        default="manual",
                        help_text="Control mode (automatic or manual)",
                        max_length=10,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this work mode configuration is active",
                    ),
                ),
                (
                    "algorithm_selected_mode",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("selling_first", "Selling First"),
                            ("zero_export_load", "Zero Export to Load"),
                            ("zero_export_ct", "Zero Export to CT"),
                        ],
                        help_text="Mode selected by algorithm when in automatic mode",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
    ]
