# Generated by Django 5.2 on 2026-03-17 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "charging_stations",
            "0026_remove_chargingsession_user_remove_invoice_user_and_more",
        ),
        ("energy", "0005_workmode"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inverter",
            name="station_id",
        ),
        migrations.AddField(
            model_name="inverter",
            name="station",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inverters",
                to="charging_stations.station",
            ),
        ),
    ]
