# Generated by Django 5.2 on 2026-04-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0006_remove_inverter_station_id_inverter_station'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(help_text='Recommended mode by algorithm', max_length=50)),
                ('ev_power_limit_kw', models.FloatField(help_text='Total power limit for EV charging')),
                ('power_per_station_kw', models.FloatField(help_text='Power per station')),
                ('battery_soc', models.FloatField(help_text='Battery SOC at time of recommendation')),
                ('pv_production_kw', models.FloatField(help_text='PV production at time of recommendation')),
                ('building_load_kw', models.FloatField(help_text='Building load at time of recommendation')),
                ('active_ev_sessions', models.IntegerField(help_text='Number of active EV sessions')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('ignored', 'Ignored'), ('expired', 'Expired')], default='pending', max_length=10)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(help_text='When this recommendation expires')),
                ('algorithm_data', models.JSONField(default=dict, help_text='Additional algorithm data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='energy_ener_status_fb208e_idx'), models.Index(fields=['expires_at'], name='energy_ener_expires_829e4f_idx')],
            },
        ),
    ]
