# Generated by Django 5.2 on 2026-04-29 12:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging_stations', '0028_metervalue_energy_wh_metervalue_power_w_and_more'),
        ('energy', '0007_energyrecommendation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energyrecommendation',
            name='active_ev_sessions',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='energyrecommendation',
            name='algorithm_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='energyrecommendation',
            name='battery_soc',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='energyrecommendation',
            name='building_load_kw',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='energyrecommendation',
            name='ev_power_limit_kw',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='energyrecommendation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 29, 12, 16, 11, 59641, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='energyrecommendation',
            name='mode',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='energyrecommendation',
            name='power_per_station_kw',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='energyrecommendation',
            name='pv_production_kw',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='gridpricing',
            name='price_per_kwh',
            field=models.DecimalField(decimal_places=4, help_text='Price in local currency per kWh', max_digits=10),
        ),
        migrations.AlterField(
            model_name='inverter',
            name='device_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='inverterreading',
            name='battery_soc',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='inverterreading',
            name='collection_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='inverterreading',
            name='connect_status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='inverterreading',
            name='generation_power',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='inverterreading',
            name='grid_power',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='inverterreading',
            name='station_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='workmode',
            name='algorithm_selected_mode',
            field=models.CharField(blank=True, choices=[('selling_first', 'Selling First'), ('zero_export_load', 'Zero Export to Load'), ('zero_export_ct', 'Zero Export to CT')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='workmode',
            name='control_mode',
            field=models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual')], default='manual', max_length=10),
        ),
        migrations.AlterField(
            model_name='workmode',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='workmode',
            name='mode',
            field=models.CharField(choices=[('selling_first', 'Selling First'), ('zero_export_load', 'Zero Export to Load'), ('zero_export_ct', 'Zero Export to CT')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='gridpricing',
            index=models.Index(fields=['start_time', 'end_time'], name='energy_grid_start_t_096876_idx'),
        ),
        migrations.AddIndex(
            model_name='inverter',
            index=models.Index(fields=['device_id'], name='energy_inve_device__affb47_idx'),
        ),
        migrations.AddIndex(
            model_name='inverter',
            index=models.Index(fields=['device_sn'], name='energy_inve_device__753e00_idx'),
        ),
    ]
