# Generated by Django 5.2 on 2026-04-29 12:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0008_alter_energyrecommendation_active_ev_sessions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energyrecommendation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 29, 12, 16, 31, 593343, tzinfo=datetime.timezone.utc)),
        ),
    ]
