# Generated by Django 5.2 on 2026-04-29 12:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0009_alter_energyrecommendation_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energyrecommendation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 29, 12, 16, 59, 819727, tzinfo=datetime.timezone.utc)),
        ),
    ]
