# Generated by Django 5.2 on 2026-05-06 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0012_alter_energyrecommendation_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energyrecommendation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 6, 17, 23, 5, 454749, tzinfo=datetime.timezone.utc)),
        ),
    ]
