# Generated by Django 5.2 on 2026-05-12 14:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0013_alter_energyrecommendation_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energyrecommendation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 12, 14, 25, 12, 469628, tzinfo=datetime.timezone.utc)),
        ),
    ]
