# Generated by Django 5.2 on 2026-05-14 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0013_alter_energyrecommendation_expires_at'),
    ]

    operations = []