# Generated by Django 5.2 on 2026-05-14 15:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0017_alter_energyrecommendation_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energyrecommendation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 14, 15, 54, 19, 549503, tzinfo=datetime.timezone.utc)),
        ),
    ]
