# Generated by Django 5.2 on 2026-05-14 16:33

from django.db import migrations, models
import renew_website.apps.api.energy.models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0018_alter_energyrecommendation_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energyrecommendation',
            name='expires_at',
            field=models.DateTimeField(default=renew_website.apps.api.energy.models.default_energy_recommendation_expires_at),
        ),
    ]
