# Generated by Django 5.2 on 2026-03-04 16:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        default="RENEW EV Charging Platform",
                        help_text="Platform name displayed throughout the system",
                        max_length=100,
                    ),
                ),
                (
                    "site_description",
                    models.TextField(
                        default="Renewable Energy EV Charging Management System",
                        help_text="Platform description",
                    ),
                ),
                (
                    "default_power_limit_kw",
                    models.DecimalField(
                        decimal_places=2,
                        default=7.4,
                        help_text="Default power limit for new charging sessions (kW)",
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(0.1),
                            django.core.validators.MaxValueValidator(350),
                        ],
                    ),
                ),
                (
                    "min_session_duration_minutes",
                    models.IntegerField(
                        default=5,
                        help_text="Minimum charging session duration (minutes)",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "session_idle_timeout_minutes",
                    models.IntegerField(
                        default=30,
                        help_text="Auto-disconnect after idle time (minutes)",
                        validators=[django.core.validators.MinValueValidator(5)],
                    ),
                ),
                (
                    "websocket_heartbeat_seconds",
                    models.IntegerField(
                        default=30,
                        help_text="WebSocket heartbeat interval (seconds)",
                        validators=[
                            django.core.validators.MinValueValidator(5),
                            django.core.validators.MaxValueValidator(300),
                        ],
                    ),
                ),
                (
                    "websocket_timeout_seconds",
                    models.IntegerField(
                        default=300,
                        help_text="WebSocket connection timeout (seconds)",
                        validators=[
                            django.core.validators.MinValueValidator(60),
                            django.core.validators.MaxValueValidator(3600),
                        ],
                    ),
                ),
                (
                    "enable_solar_optimization",
                    models.BooleanField(
                        default=True,
                        help_text="Enable solar-based charging optimization",
                    ),
                ),
                (
                    "solar_optimization_threshold_percent",
                    models.IntegerField(
                        default=70,
                        help_text="Minimum solar generation % to enable optimization",
                        validators=[
                            django.core.validators.MinValueValidator(10),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "enable_monitoring",
                    models.BooleanField(
                        default=True, help_text="Enable system health monitoring"
                    ),
                ),
                (
                    "monitoring_interval_seconds",
                    models.IntegerField(
                        default=300,
                        help_text="Health check interval (seconds)",
                        validators=[django.core.validators.MinValueValidator(60)],
                    ),
                ),
                (
                    "enable_audit_logging",
                    models.BooleanField(
                        default=True, help_text="Enable detailed audit logging"
                    ),
                ),
                (
                    "log_retention_days",
                    models.IntegerField(
                        default=90,
                        help_text="Retain logs for N days",
                        validators=[django.core.validators.MinValueValidator(7)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.CharField(
                        blank=True,
                        help_text="Last user to modify settings",
                        max_length=100,
                    ),
                ),
            ],
            options={
                "verbose_name": "System Settings",
                "verbose_name_plural": "System Settings",
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Created"),
                            ("update", "Updated"),
                            ("delete", "Deleted"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("settings_change", "Settings Changed"),
                            ("permission_change", "Permission Changed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("user", models.CharField(blank=True, max_length=150)),
                ("model_name", models.CharField(blank=True, max_length=100)),
                ("object_id", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField()),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["action", "timestamp"],
                        name="admin_setti_action_4a0e2b_idx",
                    ),
                    models.Index(
                        fields=["user", "timestamp"], name="admin_setti_user_d720c8_idx"
                    ),
                ],
            },
        ),
    ]
