# Generated by Django 5.2 on 2026-03-16 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("renew_admin", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="renew_admin_action_83e6fd_idx",
            old_name="admin_setti_action_4a0e2b_idx",
        ),
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="renew_admin_user_aeadd0_idx",
            old_name="admin_setti_user_d720c8_idx",
        ),
    ]
