# Generated by Django 5.2 on 2026-03-17 12:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WeatherLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("temp_c", models.FloatField(help_text="Temperature in Celsius")),
                ("humidity", models.FloatField(help_text="Relative humidity %")),
                ("cloud_cover", models.FloatField(help_text="Cloud cover % (0-100)")),
                (
                    "wind_kph",
                    models.FloatField(default=0.0, help_text="Wind speed in km/h"),
                ),
                (
                    "irradiance_wm2",
                    models.FloatField(
                        blank=True,
                        help_text="Global Horizontal Irradiance W/m2",
                        null=True,
                    ),
                ),
                ("source", models.CharField(default="open-meteo", max_length=50)),
                ("raw_data", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["timestamp"], name="weather_wea_timesta_658d86_idx"
                    )
                ],
            },
        ),
    ]
