# Generated by Django 5.2 on 2026-03-17 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="weatherlog",
            name="precipitation_mm",
            field=models.FloatField(default=0.0, help_text="Precipitation in mm"),
        ),
        migrations.AddField(
            model_name="weatherlog",
            name="pressure_hpa",
            field=models.FloatField(
                blank=True, help_text="Atmospheric pressure in hPa", null=True
            ),
        ),
    ]
